version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    labels:
      shipyard.route: '/'
      shipyard.init: docker-compose exec linkding python manage.py createsuperuser --username=admin --email=hello@shipyard.build
    ports:
      - "9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
